# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  fract_config = debug
endif
ifeq ($(config),release)
  fract_config = release
endif

PROJECTS := fract

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

fract:
ifneq (,$(fract_config))
	@echo "==== Building fract ($(fract_config)) ===="
	@${MAKE} --no-print-directory -C . -f fract.make config=$(fract_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f fract.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   fract"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"